config/routes.rb
PaperclipDemo::Application.routes.draw do
  resources :friends
  root :to => 'friends#index'
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  validates :name, presence: true

  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render action: 'show', status: :created, location: @friend }
      else
        format.html { render action: 'new' }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:avatar, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend, multipart: true) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit 'Make a friend' %>
    <%= link_to 'Nevermind', friends_path, class: 'button' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="friend" id="<%= friend.id %>">
  <div class="front">
    <%= link_to friend, class: 'pic-link' do %>
      <%= image_tag friend.avatar.url(:square) %>
    <% end %>
  </div>

  <div class="back">
    <span class="friend-name"><%= friend.name %></span>
    <div class="actions">
      <%= link_to 'Show', friend %>
      <%= link_to 'Edit', edit_friend_path(friend) %>
      <%= link_to 'Delete', friend, confirm: 'Are you sure you want to lose a friend?', method: :delete, class: 'destroy' %>
    </div>
  </div>
</div>

app/views/friends/edit.html.erb
<h1>Change your friend*</h1>

<%= render 'form' %>

<aside>* Do not try in real life</aside>

app/views/friends/index.html.erb
<h2>Make a new friend <%= link_to 'New Friend', new_friend_path, class: 'new-friend' %></h2>

<section id="friends">
  <%= render @friends %>
</section>

app/views/friends/new.html.erb
<h1>Make a new friend</h1>

<%= render 'form' %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @friend.name %></h2>
  <%= image_tag @friend.avatar.url(:medium) %>

<div class="show actions">
  <%= link_to 'Edit', edit_friend_path(@friend) %>
  <%= link_to 'Remove', @friend, data: { confirm: 'Are you sure you want to lose a friend?' }, method: :delete, class: 'destroy' %>
  <%= link_to 'Back to all my friends', friends_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paperclip Demo</title>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="header-wrap">
      <h1><%= link_to 'Paperclip Demo', root_path %></h1>
      <%= link_to 'Fork me on github', 'https://github.com/thoughtbot/paperclip_demo', target: 'blank', class: 'fork_me' %>
    </div>
  </header>

  <div id="main-wrap">
    <%= yield %>
  </div>

  <footer>
    <p id="copyright">© 2012 thoughtbot, inc. The <em>design of a robot</em> and <em>thoughtbot</em> are registered trademarks of <%= link_to 'thoughtbot, inc', 'http://thoughtbot.com', target: 'blank' %>.</p>
  </footer>
  <%= javascript_include_tag "application" %>
</body>
</html>